/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package School;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author 91908
 */
public class PaymentPort extends javax.swing.JFrame {

    /**
     * Creates new form PaymentPort
     */
    public PaymentPort() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rfather = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        rphone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rclass = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        rdate = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        admissioncombo = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        rtution = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        search = new javax.swing.JButton();
        rid = new javax.swing.JTextField();
        radn = new javax.swing.JTextField();
        rmess = new javax.swing.JTextField();
        rtotal = new javax.swing.JTextField();
        rbus = new javax.swing.JTextField();
        total = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        Paycombo = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        clscombo = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        yes = new javax.swing.JRadioButton();
        no = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        yes1 = new javax.swing.JRadioButton();
        no1 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 1, 36)); // NOI18N
        jLabel1.setText(" School Fees Payment Form");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Bodoni MT", 2, 18)); // NOI18N
        jLabel2.setText("ID Number");

        rname.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Bodoni MT", 2, 24)); // NOI18N
        jLabel3.setText("Student Name");

        rfather.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Book Antiqua", 3, 24)); // NOI18N
        jLabel4.setText("Father Name");

        save.setBackground(new java.awt.Color(0, 0, 0));
        save.setFont(new java.awt.Font("Bodoni MT", 1, 24)); // NOI18N
        save.setForeground(new java.awt.Color(255, 153, 153));
        save.setText("Submit");
        save.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 1, true)));
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        rphone.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Lucida Bright", 3, 18)); // NOI18N
        jLabel5.setText("Phone Number");

        rclass.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        jLabel6.setText("Course/Programme Name");

        rdate.setDateFormatString("yyyy-MM-dd");

        jLabel7.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        jLabel7.setText("Date of the Payment");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel8.setFont(new java.awt.Font("Bookman Old Style", 3, 18)); // NOI18N
        jLabel8.setText("Select What Fees you want to Pay");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setText("*");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 0, 0));
        jLabel10.setText("*");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 0, 0));
        jLabel11.setText("*");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 0, 0));
        jLabel12.setText("*");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 0, 0));
        jLabel13.setText("*");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 0, 0));
        jLabel14.setText("*");

        jLabel15.setFont(new java.awt.Font("Perpetua", 3, 18)); // NOI18N
        jLabel15.setText("Transport Charges");

        admissioncombo.setBackground(new java.awt.Color(255, 153, 153));
        admissioncombo.setFont(new java.awt.Font("Perpetua", 3, 18)); // NOI18N
        admissioncombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Mode of Admission", "Std - I Admission Fees - Rs. 10000", "Std - II Admission Fees - Rs.12500", "Std - III Admission Fees - Rs 15000", "Std- IV Admission Fees - Rs. 17500", "Std - V Admission Fees - Rs.20000" }));
        admissioncombo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        admissioncombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admissioncomboActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Perpetua", 3, 18)); // NOI18N
        jLabel16.setText("Tution Fees");

        jLabel17.setFont(new java.awt.Font("Perpetua", 3, 18)); // NOI18N
        jLabel17.setText("Mess Fees");

        rtution.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        rtution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rtutionActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        search.setIcon(new javax.swing.ImageIcon("C:\\Users\\91908\\Desktop\\school\\blksearch.png")); // NOI18N
        search.setBorderPainted(false);
        search.setContentAreaFilled(false);
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        rid.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        rid.setBorder(null);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(rid, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(rid, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        radn.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N

        rmess.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N

        rtotal.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N

        rbus.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N

        total.setBackground(new java.awt.Color(255, 153, 153));
        total.setFont(new java.awt.Font("Bodoni MT", 3, 18)); // NOI18N
        total.setText("Calculte");
        total.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jLabel18.setFont(new java.awt.Font("Bodoni MT", 3, 18)); // NOI18N
        jLabel18.setText("Total amount to Be Pay");

        Paycombo.setBackground(new java.awt.Color(255, 153, 153));
        Paycombo.setFont(new java.awt.Font("Centaur", 3, 18)); // NOI18N
        Paycombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Payment Mode", "Cash On Hand" }));
        Paycombo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel19.setFont(new java.awt.Font("Goudy Old Style", 3, 18)); // NOI18N
        jLabel19.setText("Verify and Click to Submit the Payment");

        clscombo.setBackground(new java.awt.Color(255, 102, 102));
        clscombo.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        clscombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "I", "II", "III", "IV", "V", " " }));
        clscombo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel20.setBackground(new java.awt.Color(255, 255, 0));
        jLabel20.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel20.setText("Class");

        jLabel21.setFont(new java.awt.Font("Palatino Linotype", 3, 14)); // NOI18N
        jLabel21.setIcon(new javax.swing.ImageIcon("C:\\Users\\91908\\Desktop\\school\\New folder\\bua.png")); // NOI18N

        yes.setFont(new java.awt.Font("Monospaced", 3, 12)); // NOI18N
        yes.setText("Yes");
        yes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesActionPerformed(evt);
            }
        });

        no.setFont(new java.awt.Font("Monospaced", 3, 12)); // NOI18N
        no.setText("No");
        no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\91908\\Desktop\\school\\New folder\\exit.png")); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jButton2.setText("Reset");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Californian FB", 3, 14)); // NOI18N
        jLabel22.setIcon(new javax.swing.ImageIcon("C:\\Users\\91908\\Desktop\\school\\New folder\\mess.png")); // NOI18N

        yes1.setFont(new java.awt.Font("Monospaced", 3, 12)); // NOI18N
        yes1.setText("Yes");
        yes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yes1ActionPerformed(evt);
            }
        });

        no1.setFont(new java.awt.Font("Monospaced", 3, 12)); // NOI18N
        no1.setText("No");
        no1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11))
                            .addComponent(rname, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rfather, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(rphone, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(rclass, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(rdate, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel20)
                                                                .addGap(181, 181, 181))
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(26, 26, 26)))
                                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(yes1)
                                                        .addGap(28, 28, 28)
                                                        .addComponent(no1))
                                                    .addComponent(no)
                                                    .addComponent(jButton2))
                                                .addGap(10, 10, 10))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(148, 148, 148)
                                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(115, 115, 115)
                                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(admissioncombo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(45, 45, 45)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(rbus, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(radn, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(rtution, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(rmess, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(clscombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(53, 53, 53)))
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(26, 26, 26)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel22)
                                            .addComponent(jLabel21))
                                        .addGap(32, 32, 32)
                                        .addComponent(yes)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(61, 61, 61)
                                        .addComponent(Paycombo, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(49, 49, 49)
                                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 33, Short.MAX_VALUE)
                                        .addComponent(jLabel18)
                                        .addGap(72, 72, 72)
                                        .addComponent(rtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(220, 220, 220))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addGap(55, 55, 55)
                                        .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton1)
                                        .addGap(15, 15, 15))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rname, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rfather, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rphone, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rclass, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(clscombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(19, 19, 19)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(admissioncombo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rtution, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rbus, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel21)
                                .addComponent(no)
                                .addComponent(yes)))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rmess, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)
                            .addComponent(no1)
                            .addComponent(yes1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Paycombo)
                            .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(rtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void admissioncomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admissioncomboActionPerformed
        double admission,tution,bus;
        switch(admissioncombo.getSelectedIndex()){
          case 1:
              admission=10000;  
              tution=1500;
           radn.setText(Double.toString(admission));
           rtution.setText(Double.toString(tution));
               break;
          case 2:
              admission=12500;
              tution=2000;
           radn.setText(Double.toString(admission));
           rtution.setText(Double.toString(tution));
           break;
          case 3:
              admission=15000;
              tution=2500;
           radn.setText(Double.toString(admission));
           rtution.setText(Double.toString(tution));
           break;
         case 4:
               admission=17500;
              tution=3000;
           radn.setText(Double.toString(admission));
           rtution.setText(Double.toString(tution));
           break;
          case 5:
               admission=20000;
              tution=3500;
           radn.setText(Double.toString(admission));
           rtution.setText(Double.toString(tution));
        break;
        }
        
         
               
    }//GEN-LAST:event_admissioncomboActionPerformed

    private void rtutionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rtutionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rtutionActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
       double bus,total,tution,admission,mess;
        switch(Paycombo.getSelectedIndex()){
           case 0:
               JOptionPane.showMessageDialog(this,"Please select the Payment Mode");
               break;
           case 1:
              bus=Double.parseDouble(rbus.getText());
              tution=Double.parseDouble(rtution.getText());
              mess=Double.parseDouble(rmess.getText());
              admission=Double.parseDouble(radn.getText());
               total=bus+mess+tution+admission;
               rtotal.setText(Double.toString(total));
               break;
               }
       
    }//GEN-LAST:event_totalActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        rbus.setText("");
        rtution.setText("");
        rmess.setText("");
        rtotal.setText("");
        rtotal.setEnabled(true);
        radn.setText("");
       yes1.setSelected(false);
       no1.setSelected(false);
        yes.setSelected(false);
        no.setSelected(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        String name,father,Mobile,course;
        try{
        Class.forName("java.sql.DriverManager");
        Connection con=(Connection) DriverManager.getConnection
            ("jdbc:mysql://localhost:3306/schoolmanagement","root","Mp@0509");
        Statement st=(Statement) con.createStatement();
        String id=rid.getText();
        
        switch(clscombo.getSelectedIndex()){
            case 0:
                String que1="Select name,father,Mobile,course from admission1 where id='"+id+"';";
                ResultSet rs=st.executeQuery(que1);
                int search=0;
                while(rs.next()){
                    name=rs.getString("name");
                    father=rs.getString("father");
                    Mobile=rs.getString("Mobile");
                    course=rs.getString("course");
                    rname.setText(name);
                    rfather.setText(father);
                    rphone.setText(Mobile);
                    rclass.setText(course);
                    search++;
                }
                if(search==0)
                    JOptionPane.showMessageDialog(this,"No Id Number is Search found");
                break;
            case 1:
                 String que2="Select name,father,Mobile,course from admission2 where id='"+id+"';";
                ResultSet rs1=st.executeQuery(que2);
                search=0;
                while(rs1.next()){
                    name=rs1.getString("name");
                    father=rs1.getString("father");
                    Mobile=rs1.getString("Mobile");
                    course=rs1.getString("course");
                    rname.setText(name);
                    rfather.setText(father);
                    rphone.setText(Mobile);
                    rclass.setText(course);
                    search++;
                }
                if(search==0)
                    JOptionPane.showMessageDialog(this,"No Id Number is Search found");
                break;
            case 2:
                 String que3="Select name,father,Mobile,course from admission3 where id='"+id+"';";
                ResultSet rs2=st.executeQuery(que3);
                search=0;
                while(rs2.next()){
                    name=rs2.getString("name");
                    father=rs2.getString("father");
                    Mobile=rs2.getString("Mobile");
                    course=rs2.getString("course");
                    rname.setText(name);
                    rfather.setText(father);
                    rphone.setText(Mobile);
                    rclass.setText(course);
                    search++;
                }
                if(search==0)
                    JOptionPane.showMessageDialog(this,"No Id Number is Search found");
                break;
            case 3:
                 String que4="Select name,father,Mobile,course from admission4 where id='"+id+"';";
                ResultSet rs4=st.executeQuery(que4);
                search=0;
                while(rs4.next()){
                    name=rs4.getString("name");
                    father=rs4.getString("father");
                    Mobile=rs4.getString("Mobile");
                    course=rs4.getString("course");
                    rname.setText(name);
                    rfather.setText(father);
                    rphone.setText(Mobile);
                    rclass.setText(course);
                    search++;
                }
                if(search==0)
                    JOptionPane.showMessageDialog(this,"No Id Number is Search found");
                break;
            case 4:
                 String que5="Select name,father,Mobile,course from admission5 where id='"+id+"';";
                ResultSet rs5=st.executeQuery(que5);
                search=0;
                while(rs5.next()){
                    name=rs5.getString("name");
                    father=rs5.getString("father");
                    Mobile=rs5.getString("Mobile");
                    course=rs5.getString("course");
                    rname.setText(name);
                    rfather.setText(father);
                    rphone.setText(Mobile);
                    rclass.setText(course);
                    search++;
                }
                if(search==0)
                    JOptionPane.showMessageDialog(this,"No Id Number is Search found");
                break;
        }}
        catch(Exception e){
                JOptionPane.showMessageDialog(this,e.getMessage());
                }
    }//GEN-LAST:event_searchActionPerformed

    private void yesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesActionPerformed
      double bus=3000.00;
      rbus.setText(Double.toString(bus));
      no.setSelected(false);
        
    }//GEN-LAST:event_yesActionPerformed

    private void noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noActionPerformed
        double bus=0.00;
        rbus.setText(Double.toString(bus));
        yes.setSelected(false);
    }//GEN-LAST:event_noActionPerformed

    private void yes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yes1ActionPerformed
        double mess=2500;
        rmess.setText(Double.toString(mess));
        no1.setSelected(false);
    }//GEN-LAST:event_yes1ActionPerformed

    private void no1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no1ActionPerformed
        double mess=0.0;
        rmess.setText(Double.toString(mess));
        yes1.setSelected(false);
    }//GEN-LAST:event_no1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      StudentFees sf=new StudentFees();
      sf.show();
      dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        String name,id,father,mobile,pay,mess,tution,total,admission,bus,std;
        name=rname.getText();
        father=rfather.getText();
        mobile=rphone.getText();
        mess=rmess.getText();
        tution=rtution.getText();
        admission=radn.getText();
        std=rclass.getText();
        bus=rbus.getText();
        total=rtotal.getText();
               id=rid.getText();
SimpleDateFormat sf=new SimpleDateFormat("yyyy-MM-dd");
              pay=sf.format(rdate.getDate());
              
              try{
               Class.forName("java.sql.DriverManager");
        Connection con=(Connection) DriverManager.getConnection
            ("jdbc:mysql://localhost:3306/schoolmanagement","root","Mp@0509");
        Statement st=(Statement) con.createStatement();
        switch(clscombo.getSelectedIndex()){
            case 0:
            String query="Insert into paymentlist values('"+id+"','"+name+"','"+father+"','"+mobile+"','"+std+"','"+pay+"','"+admission+"','"+tution+"','"+bus+"','"+mess+"','"+total+"');";
        st.executeUpdate(query);
        JOptionPane.showMessageDialog(this,"Payment successfully");
        break;
        case 1:
            String que="Insert into Paymentlist values('"+id+"','"+name+"','"+father+"','"+mobile+"','"+std+"','"+pay+"','"+admission+"','"+tution+"','"+bus+"','"+mess+"','"+total+"');";
        st.executeUpdate(que);
        JOptionPane.showMessageDialog(this,"Payment successfully");
        break;
        case 2:
            String quer="Insert into Paymentlist values('"+id+"','"+name+"','"+father+"','"+mobile+"','"+std+"','"+pay+"','"+admission+"','"+tution+"','"+bus+"','"+mess+"','"+total+"');";
        st.executeUpdate(quer);
        JOptionPane.showMessageDialog(this,"Payment successfully");
        break;
        case 3:
            String qery="Insert into Paymentlist values('"+id+"','"+name+"','"+father+"','"+mobile+"','"+std+"','"+pay+"','"+admission+"','"+tution+"','"+bus+"','"+mess+"','"+total+"');";
        st.executeUpdate(qery);
        JOptionPane.showMessageDialog(this,"Payment successfully");
        break;
        case 4:
            String qury="Insert into Paymentlist values('"+id+"','"+name+"','"+father+"','"+mobile+"','"+std+"','"+pay+"','"+admission+"','"+tution+"','"+bus+"','"+mess+"','"+total+"');";
        st.executeUpdate(qury);
        JOptionPane.showMessageDialog(this,"Payment successfully");
        break;
        }}
              catch(Exception e){
                  JOptionPane.showMessageDialog(this,e.getMessage());
              }
    }//GEN-LAST:event_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentPort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentPort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentPort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentPort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaymentPort().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Paycombo;
    private javax.swing.JComboBox<String> admissioncombo;
    private javax.swing.JComboBox<String> clscombo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JRadioButton no;
    private javax.swing.JRadioButton no1;
    private javax.swing.JTextField radn;
    private javax.swing.JTextField rbus;
    private javax.swing.JTextField rclass;
    private com.toedter.calendar.JDateChooser rdate;
    private javax.swing.JTextField rfather;
    private javax.swing.JTextField rid;
    private javax.swing.JTextField rmess;
    private javax.swing.JTextField rname;
    private javax.swing.JTextField rphone;
    private javax.swing.JTextField rtotal;
    private javax.swing.JTextField rtution;
    private javax.swing.JButton save;
    private javax.swing.JButton search;
    private javax.swing.JButton total;
    private javax.swing.JRadioButton yes;
    private javax.swing.JRadioButton yes1;
    // End of variables declaration//GEN-END:variables
}
