/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package School;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author 91908
 */
public class ReportDetails extends javax.swing.JFrame {

    /**
     * Creates new form ReportDetails
     */
    public ReportDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        id2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        idno = new javax.swing.JTextField();
        st = new javax.swing.JTextField();
        sname = new javax.swing.JTextField();
        se = new javax.swing.JTextField();
        sm = new javax.swing.JTextField();
        ss = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        ave = new javax.swing.JTextField();
        stot = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        soc = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        sgrade = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        search = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton8 = new javax.swing.JButton();
        cmt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1080, 650));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(950, 619));

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));

        jComboBox1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(0, 0, 204));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Class - I", "Class - II", "Class - III", "Class - IV", "Class - V" }));

        jLabel2.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Student ID Number");

        jLabel3.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Student Name");

        idno.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N

        st.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N

        sname.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N

        se.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N

        sm.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N

        ss.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Mathematics");

        jLabel5.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Science");

        jLabel6.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("English");

        jLabel7.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tamil");

        jButton2.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 204));
        jButton2.setText("Total");
        jButton2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 255), null), new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 2, true)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        ave.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N

        stot.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Average(%)");

        jLabel9.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Grade");

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(0, 0, 255));
        jRadioButton1.setText("Grade 'A'");
        jRadioButton1.setBorderPainted(true);
        jRadioButton1.setOpaque(true);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(0, 0, 255));
        jRadioButton2.setText("Grade 'B\"");
        jRadioButton2.setBorderPainted(true);
        jRadioButton2.setOpaque(true);
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(0, 0, 255));
        jRadioButton3.setText("Grade 'C'");
        jRadioButton3.setBorderPainted(true);
        jRadioButton3.setOpaque(true);
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Social Science");

        soc.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N

        jButton1.setBackground(new java.awt.Color(0, 0, 204));
        jButton1.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 204));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\91908\\Desktop\\school\\icon\\go.jpg")); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        sgrade.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Average(%)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(se, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                            .addComponent(st, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ss))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jRadioButton1)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jRadioButton2)
                                .addComponent(jRadioButton3))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(sgrade, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(stot, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addGap(274, 274, 274))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(120, 120, 120)
                                .addComponent(jLabel3))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(idno, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(sname, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(147, 147, 147)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(soc, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sm, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(ave, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(idno, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sname, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(57, 57, 57)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(st, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(se, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton1))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ss, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton3)
                    .addComponent(soc, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sgrade, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sm, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(stot, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ave, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Students Marks Report Enrollment");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));

        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 0, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Number", "Name", "Tamil", "English", "Science", "Social", "Social Science", "Total", "Average(%)", "Grade", "Comments"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setSelectionBackground(new java.awt.Color(0, 0, 204));
        jTable1.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jTable1.setShowGrid(true);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        search.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        search.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 1, true));

        jButton3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 204));
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\91908\\Desktop\\school\\icon\\add-file-512.png")); // NOI18N
        jButton3.setText("Add");
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 204));
        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\91908\\Desktop\\school\\icon\\edit.png")); // NOI18N
        jButton4.setText("Update");
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 204));
        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\91908\\Desktop\\school\\icon\\del.png")); // NOI18N
        jButton5.setText("Delete");
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 0, 204));
        jButton6.setIcon(new javax.swing.ImageIcon("C:\\Users\\91908\\Desktop\\school\\icon\\close.jpg")); // NOI18N
        jButton6.setText("Close");
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);

        jList1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jList1.setForeground(new java.awt.Color(0, 0, 204));
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "(80-100)Grade A", "(60-80)Grade B", "(40-60)Grade C", "40 Below No Grades" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionBackground(new java.awt.Color(0, 0, 204));
        jList1.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(jList1);

        jButton8.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(0, 0, 255));
        jButton8.setIcon(new javax.swing.ImageIcon("C:\\Users\\91908\\Desktop\\school\\icon\\search.png")); // NOI18N
        jButton8.setText("search");
        jButton8.setBorderPainted(false);
        jButton8.setContentAreaFilled(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        cmt.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        cmt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 1, true));

        jLabel10.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 204));
        jLabel10.setText("Add Comments");

        jButton7.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 0, 255));
        jButton7.setIcon(new javax.swing.ImageIcon("C:\\Users\\91908\\Desktop\\school\\icon\\reset.jpg")); // NOI18N
        jButton7.setText("Reset");
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(51, 0, 204));
        jButton9.setIcon(new javax.swing.ImageIcon("C:\\Users\\91908\\Desktop\\school\\icon\\show.png")); // NOI18N
        jButton9.setText("View All");
        jButton9.setBorderPainted(false);
        jButton9.setContentAreaFilled(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel12.setText("Enter ID number");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jButton3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton5))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(cmt, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addGap(85, 85, 85)
                                        .addComponent(jLabel10))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton8)
                                .addGap(18, 18, 18)
                                .addComponent(jButton9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton7))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3350, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(39, 39, 39))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton8)
                            .addComponent(jButton9)
                            .addComponent(jButton7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton4)
                            .addComponent(jButton5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addGap(1, 1, 1)
                        .addComponent(cmt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jButton10.setIcon(new javax.swing.ImageIcon("C:\\Users\\91908\\Desktop\\school\\icon\\back.jpg")); // NOI18N
        jButton10.setBorderPainted(false);
        jButton10.setContentAreaFilled(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(71, 71, 71))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1052, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    String no,name,grade;
    Double tamil,english,science,maths,total,avg,socil;
    no=idno.getText();
    name=sname.getText();
   tamil=Double.parseDouble(st.getText());
   english=Double.parseDouble(se.getText());
   science=Double.parseDouble(ss.getText());
   maths=Double.parseDouble(sm.getText());
   socil=Double.parseDouble(soc.getText());
   total=tamil+english+science+maths+socil;
   avg=(total/500)*100;
   stot.setText(Double.toString(total));
   ave.setText(Double.toString(avg));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
     sgrade.setText("A");
     cmt.setText("Excellent");
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        sgrade.setText("B"); 
        cmt.setText("Good");
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        sgrade.setText("C");
        cmt.setText("Fair");
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String id,name;
        id=idno.getText();
        try{
             Class.forName("java.sql.DriverManager");
         Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/schoolmanagement","root","Mp@0509");
         Statement st=(Statement) con.createStatement();
        switch(jComboBox1.getSelectedIndex()){
            case 0:
                String query="Select name from Admission1 where id='"+id+"';";
                ResultSet rs=st.executeQuery(query);
                int search=0;
                while(rs.next()){
                    name=rs.getString("name");
                    sname.setText(name);
                    search++;
                }
                break;
            case 1:
                 String query1="Select name from Admission2 where id='"+id+"';";
                ResultSet rs1=st.executeQuery(query1);
                search=0;
               while(rs1.next()){
                    name=rs1.getString("name");
                    sname.setText(name);
                    search++;
                }
               break;
            case 2:
                 String query2="Select name from Admission3 where id='"+id+"';";
                ResultSet rs2=st.executeQuery(query2);
                search=0;
                while(rs2.next()){
                    name=rs2.getString("name");
                    sname.setText(name);
                    search++;
                }
                break;
            case 3:
                 String query3="Select name from Admission4 where id='"+id+"';";
                ResultSet rs3=st.executeQuery(query3);
                search=0;
                while(rs3.next()){
                    name=rs3.getString("name");
                    sname.setText(name);
                    search++;
                }
                break;
            case 4:
                 String query4="Select name from Admission5 where id='"+id+"';";
                ResultSet rs4=st.executeQuery(query4);
                search=0;
                while(rs4.next()){
                    name=rs4.getString("name");
                    sname.setText(name);
                    search++;
                }
        break;
        
      
        }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        String no,name,grade,comments;
        String tam,eng,sci,ssci,mat,total,aveg;
         no=idno.getText();
    name=sname.getText();
   tam=st.getText();
   eng=se.getText();
   sci=ss.getText();
   mat=sm.getText();
   ssci=soc.getText();
   total=stot.getText();
   aveg=ave.getText();
   grade=sgrade.getText();
  comments=cmt.getText();
  DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
    try{
             Class.forName("java.sql.DriverManager");
         Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/schoolmanagement","root","Mp@0509");
         Statement st=(Statement) con.createStatement();
       
        
        switch(jComboBox1.getSelectedIndex()){
            case 0:
                String query="Insert into result1 values('"+no+"','"+name+"','"+tam+"','"+eng+"','"+sci+"','"+ssci+"','"+mat+"','"+total+"','"+aveg+"','"+grade+"','"+comments+"');";
                st.executeUpdate(query);
                 String[] row={no,name,tam,eng,sci,ssci,mat,total,aveg,grade,comments};
                model.addRow(row);
                break;
            case 1:
                String query1="Insert into result2 values('"+no+"','"+name+"','"+tam+"','"+eng+"','"+sci+"','"+ssci+"','"+mat+"','"+total+"','"+aveg+"','"+grade+"','"+comments+"');";
                st.executeUpdate(query1);
                 
                String[] row1={no,name,tam,eng,sci,ssci,mat,total,aveg,grade,comments};
                model.addRow(row1);
                break;
            case 2:
                String query2="Insert into result3 values('"+no+"','"+name+"','"+tam+"','"+eng+"','"+sci+"','"+ssci+"','"+mat+"','"+total+"','"+aveg+"','"+grade+"','"+comments+"');";
                st.executeUpdate(query2);
                 
                String[] row2={no,name,tam,eng,sci,ssci,mat,total,aveg,grade,comments};
                model.addRow(row2);
                break;
            case 3:
                String query3="Insert into result4 values('"+no+"','"+name+"','"+tam+"','"+eng+"','"+sci+"','"+ssci+"','"+mat+"','"+total+"','"+aveg+"','"+grade+"','"+comments+"');";
                st.executeUpdate(query3);
                
                String[] row3={no,name,tam,eng,sci,ssci,mat,total,aveg,grade,comments};
                model.addRow(row3);
                break;
            case 4:
                String query4="Insert into result5 values('"+no+"','"+name+"','"+tam+"','"+eng+"','"+sci+"','"+ssci+"','"+mat+"','"+total+"','"+aveg+"','"+grade+"','"+comments+"');";
                st.executeUpdate(query4);
                
                String[] row4={no,name,tam,eng,sci,ssci,mat,total,aveg,grade,comments};
                model.addRow(row4);
                break;
        }
   
       }
    catch(Exception e){
        System.out.println(e);
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
         DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
           int i=jTable1.getSelectedRow();
            model.removeRow(i);
        String no,name,grade,comments;
        String tam,eng,sci,ssci,mat,total,aveg;
         no=idno.getText();
    name=sname.getText();
   tam=st.getText();
   eng=se.getText();
   sci=ss.getText();
   mat=sm.getText();
   ssci=soc.getText();
   total=stot.getText();
   aveg=ave.getText();
   grade=sgrade.getText();
 
   comments=cmt.getText();
    try{
             Class.forName("java.sql.DriverManager");
         Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/schoolmanagement","root","Mp@0509");
         Statement st=(Statement) con.createStatement();
       
        switch(jComboBox1.getSelectedIndex()){
            case 0:
                String query="update result1 set tam='"+tam+"',eng='"+eng+"',sci='"+sci+"',ssci='"+ssci+"',mat='"+mat+"',total='"+total+"',aveg='"+aveg+"',grade='"+grade+"',comments='"+comments+"' where no='"+no+"';";
                st.executeUpdate(query);
                String[] row={no,name,tam,eng,sci,ssci,mat,total,aveg,grade,comments};
                model.addRow(row);
                break;
            case 1:
                  String query1="update result2 set tam='"+tam+"',eng='"+eng+"',sci='"+sci+"',ssci='"+ssci+"',mat='"+mat+"',total='"+total+"',aveg='"+aveg+"',grade='"+grade+"',comments='"+comments+"' where no='"+no+"';";
                st.executeUpdate(query1);
                String[] row1={no,name,tam,eng,sci,ssci,mat,total,aveg,grade,comments};
                model.addRow(row1);
                break;
            case 2:
                String query2="update result3 set tam='"+tam+"',eng='"+eng+"',sci='"+sci+"',ssci='"+ssci+"',mat='"+mat+"',total='"+total+"',aveg='"+aveg+"',grade='"+grade+"',comments='"+comments+"' where no='"+no+"';";
                st.executeUpdate(query2);
                String[] row2={no,name,tam,eng,sci,ssci,mat,total,aveg,grade,comments};
                model.addRow(row2);
                break;
            case 3:
                 String query3="update result4 set tam='"+tam+"',eng='"+eng+"',sci='"+sci+"',ssci='"+ssci+"',mat='"+mat+"',total='"+total+"',aveg='"+aveg+"',grade='"+grade+"',comments='"+comments+"' where no='"+no+"';";
                st.executeUpdate(query3);
                String[] row3={no,name,tam,eng,sci,ssci,mat,total,aveg,grade,comments};
                model.addRow(row3);
                break;
            case 4:
               String query4="update result5 set tam='"+tam+"',eng='"+eng+"',sci='"+sci+"',ssci='"+ssci+"',mat='"+mat+"',total='"+total+"',aveg='"+aveg+"',grade='"+grade+"',comments='"+comments+"' where no='"+no+"';";
                st.executeUpdate(query4);
                String[] row4={no,name,tam,eng,sci,ssci,mat,total,aveg,grade,comments};
                model.addRow(row4);
                break;
        }
                JOptionPane.showMessageDialog(this,"succesfully Updated");        

}
    catch(Exception e){
        System.out.println(e);
    }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int i=jTable1.getSelectedRow();
       DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
       idno.setText(model.getValueAt(i,0).toString());
       sname.setText(model.getValueAt(i,1).toString());
       st.setText(model.getValueAt(i,2).toString());
       se.setText(model.getValueAt(i,3).toString());
       ss.setText(model.getValueAt(i,4).toString());
       sm.setText(model.getValueAt(i,6).toString());
       soc.setText(model.getValueAt(i,5).toString());
       stot.setText(model.getValueAt(i,7).toString());
       ave.setText(model.getValueAt(i,8).toString());
       sgrade.setText(model.getValueAt(i,9).toString());
       cmt.setText(model.getValueAt(i,10).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        idno.setText("");
        sname.setText("");st.setText("");se.setText("");sm.setText("");soc.setText("");stot.setText("");
        ave.setText("");sgrade.setText("");
        ss.setText("");
        jRadioButton1.setSelected(false);
        jRadioButton2.setSelected(false);
        jRadioButton3.setSelected(false);
        cmt.setText("");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String no,name,grade,comments,tam,eng,sci,ssci,mat,total,aveg;
         
         DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
       while(model.getRowCount()>0){
          model.removeRow(0);}
        try{
             Class.forName("java.sql.DriverManager");
         Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/schoolmanagement","root","Mp@0509");
         Statement st=(Statement) con.createStatement();
          switch(jComboBox1.getSelectedIndex()){
             case 0:
                 String que="Select* from result1;";
                 ResultSet rs=st.executeQuery(que);
                  int search=0;
        while(rs.next()){
              
               no=rs.getString(1);
             name=rs.getString(2);
             tam=rs.getString(3);
             eng=rs.getString(4);
             sci=rs.getString(5);
             
             ssci=rs.getString(6);
             mat=rs.getString(7);
             total=rs.getString(8);
             aveg=rs.getString(9);
             grade=rs.getString(10);
             comments=rs.getString(11);
             String[] row={no,name,tam,eng,sci,ssci,mat,total,aveg,grade,comments};
             model.addRow(row);
             search++;
         }
          if(search==0)
            JOptionPane.showMessageDialog(this,"NO search Name is found");
        break;
             case 1:
                 String que1="Select* from result2;";
                 ResultSet rs1=st.executeQuery(que1);
                  search=0;
        while(rs1.next()){
              
               no=rs1.getString(1);
             name=rs1.getString(2);
             tam=rs1.getString(3);
             eng=rs1.getString(4);
             sci=rs1.getString(5);
             mat=rs1.getString(7);
             ssci=rs1.getString(6);
             total=rs1.getString(8);
             aveg=rs1.getString(9);
             grade=rs1.getString(10);
             comments=rs1.getString(11);
             String[] row={no,name,tam,eng,sci,ssci,mat,total,aveg,grade,comments};
             model.addRow(row);
             search++;
         }
          if(search==0)
            JOptionPane.showMessageDialog(this,"NO search Name is found");
        break;
             case 2:
                 String que2="Select* from result3;";
                 ResultSet rs2=st.executeQuery(que2);
                  search=0;
        while(rs2.next()){
              
               no=rs2.getString(1);
             name=rs2.getString(2);
             tam=rs2.getString(3);
             eng=rs2.getString(4);
             sci=rs2.getString(5);
             mat=rs2.getString(7);
             ssci=rs2.getString(6);
             total=rs2.getString(8);
             aveg=rs2.getString(9);
             grade=rs2.getString(10);
             comments=rs2.getString(11);
             String[] row={no,name,tam,eng,sci,ssci,mat,total,aveg,grade,comments};
             model.addRow(row);
             search++;
         }
          if(search==0)
            JOptionPane.showMessageDialog(this,"NO search Name is found");
        break;
             case 3:
                 String que3="Select* from result4;";
                 ResultSet rs3=st.executeQuery(que3);
                  search=0;
        while(rs3.next()){
              
               no=rs3.getString(1);
             name=rs3.getString(2);
             tam=rs3.getString(3);
             eng=rs3.getString(4);
             sci=rs3.getString(5);
             mat=rs3.getString(7);
             ssci=rs3.getString(6);
             total=rs3.getString(8);
             aveg=rs3.getString(9);
             grade=rs3.getString(10);
             comments=rs3.getString(11);
             String[] row={no,name,tam,eng,sci,ssci,mat,total,aveg,grade,comments};
             model.addRow(row);
             search++;
         }
          if(search==0)
            JOptionPane.showMessageDialog(this,"NO search Name is found");
        break;
             case 4:
                 String que4="Select* from result5;";
                 ResultSet rs4=st.executeQuery(que4);
                  search=0;
        while(rs4.next()){
              
               no=rs4.getString(1);
             name=rs4.getString(2);
             tam=rs4.getString(3);
             eng=rs4.getString(4);
             sci=rs4.getString(5);
             mat=rs4.getString(7);
             ssci=rs4.getString(6);
             total=rs4.getString(8);
             aveg=rs4.getString(9);
             grade=rs4.getString(10);
             comments=rs4.getString(11);
             String[] row={no,name,tam,eng,sci,ssci,mat,total,aveg,grade,comments};
             model.addRow(row);
             search++;
         }
          if(search==0)
            JOptionPane.showMessageDialog(this,"NO search Name is found");
        break;
          }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
         DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
          String no,name,grade,comments,tam,eng,sci,ssci,mat,total,aveg;
       while(model.getRowCount()>0){
          model.removeRow(0);}
        try{
             Class.forName("java.sql.DriverManager");
         Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/schoolmanagement","root","Mp@0509");
         Statement st=(Statement) con.createStatement();
         name=search.getText();
          switch(jComboBox1.getSelectedIndex()){
             case 0:
                 String que="Select* from result1 where name='"+name+"';";
                 ResultSet rs=st.executeQuery(que);
                  int search=0;
        while(rs.next()){
              
               no=rs.getString(1);
             name=rs.getString(2);
             tam=rs.getString(3);
             eng=rs.getString(4);
             sci=rs.getString(5);
             
             ssci=rs.getString(6);
             mat=rs.getString(7);
             total=rs.getString(8);
             aveg=rs.getString(9);
             grade=rs.getString(10);
             comments=rs.getString(11);
             String[] row={no,name,tam,eng,sci,ssci,mat,total,aveg,grade,comments};
             model.addRow(row);
             search++;
         }
          if(search==0)
            JOptionPane.showMessageDialog(this,"NO search Name is found");
        break;
             case 1:
                 String que1="Select* from result2 where name='"+name+"';";
                 ResultSet rs1=st.executeQuery(que1);
                  search=0;
        while(rs1.next()){
              
               no=rs1.getString(1);
             name=rs1.getString(2);
             tam=rs1.getString(3);
             eng=rs1.getString(4);
             sci=rs1.getString(5);
             mat=rs1.getString(7);
             ssci=rs1.getString(6);
             total=rs1.getString(8);
             aveg=rs1.getString(9);
             grade=rs1.getString(10);
             comments=rs1.getString(11);
             String[] row={no,name,tam,eng,sci,ssci,mat,total,aveg,grade,comments};
             model.addRow(row);
             search++;
         }
          if(search==0)
            JOptionPane.showMessageDialog(this,"NO search Name is found");
        break;
             case 2:
                 String que2="Select* from result3 where name='"+name+"';";
                 ResultSet rs2=st.executeQuery(que2);
                  search=0;
        while(rs2.next()){
              
               no=rs2.getString(1);
             name=rs2.getString(2);
             tam=rs2.getString(3);
             eng=rs2.getString(4);
             sci=rs2.getString(5);
             mat=rs2.getString(7);
             ssci=rs2.getString(6);
             total=rs2.getString(8);
             aveg=rs2.getString(9);
             grade=rs2.getString(10);
             comments=rs2.getString(11);
             String[] row={no,name,tam,eng,sci,ssci,mat,total,aveg,grade,comments};
             model.addRow(row);
             search++;
         }
          if(search==0)
            JOptionPane.showMessageDialog(this,"NO search Name is found");
        break;
             case 3:
                 String que3="Select* from result4 where name='"+name+"';";
                 ResultSet rs3=st.executeQuery(que3);
                  search=0;
        while(rs3.next()){
              
               no=rs3.getString(1);
             name=rs3.getString(2);
             tam=rs3.getString(3);
             eng=rs3.getString(4);
             sci=rs3.getString(5);
             mat=rs3.getString(7);
             ssci=rs3.getString(6);
             total=rs3.getString(8);
             aveg=rs3.getString(9);
             grade=rs3.getString(10);
             comments=rs3.getString(11);
             String[] row={no,name,tam,eng,sci,ssci,mat,total,aveg,grade,comments};
             model.addRow(row);
             search++;
         }
          if(search==0)
            JOptionPane.showMessageDialog(this,"NO search Name is found");
        break;
             case 4:
                 String que4="Select* from result5 where name='"+name+"';";
                 ResultSet rs4=st.executeQuery(que4);
                  search=0;
        while(rs4.next()){
              
               no=rs4.getString(1);
             name=rs4.getString(2);
             tam=rs4.getString(3);
             eng=rs4.getString(4);
             sci=rs4.getString(5);
             mat=rs4.getString(7);
             ssci=rs4.getString(6);
             total=rs4.getString(8);
             aveg=rs4.getString(9);
             grade=rs4.getString(10);
             comments=rs4.getString(11);
             String[] row={no,name,tam,eng,sci,ssci,mat,total,aveg,grade,comments};
             model.addRow(row);
             search++;
         }
          if(search==0)
            JOptionPane.showMessageDialog(this,"NO search Name is found");
        break;
          }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String name=sname.getText();
        try{
         Class.forName("java.sql.DriverManager");
         Connection con=(Connection)
                 DriverManager.getConnection("jdbc:mysql://localhost:3306/schoolmanagement","root","Mp@0509");
         Statement st=(Statement) con.createStatement();
         switch(jComboBox1.getSelectedIndex()){
         case 0:
             String q="Delete from result1 where name='"+name+"'";
             st.execute(q);
             JOptionPane.showMessageDialog(this,"Data is successfully Deleted");
             break;
         case 1:
               String q1="Delete from result2 where name='"+name+"'";
             st.execute(q1);
             JOptionPane.showMessageDialog(this,"Data is successfully Deleted");
             break;
         case 2:
               String q2="Delete from result3 where name='"+name+"'";
             st.execute(q2);
             JOptionPane.showMessageDialog(this,"Data is successfully Deleted");
             break;
         case 3:
               String q3="Delete from result4 where name='"+name+"'";
             st.execute(q3);
             JOptionPane.showMessageDialog(this,"Data is successfully Deleted");
             break;
         case 4:
               String s="Delete from result5 where name='"+name+"'";
             st.execute(s);
             JOptionPane.showMessageDialog(this,"Data is successfully Deleted");
             break;
     }
         DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
         int Index=jTable1.getSelectedRow();
         model.removeRow(Index);}
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        StudentAttendance sa=new StudentAttendance();
        sa.show();
        dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ave;
    private javax.swing.JTextField cmt;
    private javax.swing.JTextField id2;
    private javax.swing.JTextField idno;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField se;
    private javax.swing.JTextField search;
    private javax.swing.JTextField sgrade;
    private javax.swing.JTextField sm;
    private javax.swing.JTextField sname;
    private javax.swing.JTextField soc;
    private javax.swing.JTextField ss;
    private javax.swing.JTextField st;
    private javax.swing.JTextField stot;
    // End of variables declaration//GEN-END:variables
}
