/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package School;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
/**
 *
 * @author 91908
 */
public class SAttendance extends javax.swing.JFrame {

    /**
     * Creates new form SAttendance
     */
    public SAttendance() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        search = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sname = new javax.swing.JTextField();
        sid = new javax.swing.JTextField();
        sclass = new javax.swing.JTextField();
        sdate = new com.toedter.calendar.JDateChooser();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jLabel1.setFont(new java.awt.Font("Lucida Fax", 3, 18)); // NOI18N
        jLabel1.setText("Student Attendance Entry Report");

        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\91908\\Desktop\\school\\New folder\\search.png")); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        search.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Lucida Bright", 3, 12)); // NOI18N
        jLabel2.setText("Name");

        jLabel3.setFont(new java.awt.Font("Lucida Bright", 3, 12)); // NOI18N
        jLabel3.setText("Class");

        jLabel4.setFont(new java.awt.Font("Lucida Bright", 3, 12)); // NOI18N
        jLabel4.setText("ID Number");

        jLabel5.setFont(new java.awt.Font("Lucida Bright", 3, 12)); // NOI18N
        jLabel5.setText("Attendance");

        jLabel6.setFont(new java.awt.Font("Lucida Bright", 3, 12)); // NOI18N
        jLabel6.setText("Date");

        sname.setBackground(new java.awt.Color(0, 0, 0));
        sname.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        sname.setForeground(new java.awt.Color(255, 255, 255));

        sid.setBackground(new java.awt.Color(0, 0, 0));
        sid.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        sid.setForeground(new java.awt.Color(255, 255, 255));

        sclass.setBackground(new java.awt.Color(0, 0, 0));
        sclass.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        sclass.setForeground(new java.awt.Color(255, 255, 255));

        sdate.setBackground(new java.awt.Color(255, 255, 255));
        sdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sdate.setDateFormatString("yyyy-MM-dd");

        jRadioButton1.setFont(new java.awt.Font("Lucida Bright", 3, 12)); // NOI18N
        jRadioButton1.setText("Present");

        jRadioButton2.setFont(new java.awt.Font("Lucida Bright", 3, 12)); // NOI18N
        jRadioButton2.setText("Absent");

        jButton2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jButton2.setText("Reset");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\91908\\Desktop\\school\\New folder\\sae.png")); // NOI18N
        jButton3.setText("Save");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\91908\\Desktop\\school\\New folder\\close.png")); // NOI18N
        jButton4.setText("close");
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jComboBox1.setBackground(new java.awt.Color(0, 0, 0));
        jComboBox1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Std - I", "Std -II", "Std - III", "Std - IV", "Std - V" }));
        jComboBox1.setBorder(null);

        jLabel7.setText("Enter ID Number");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jButton4)
                .addGap(36, 36, 36))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(sid, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sdate, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sclass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton1)
                        .addGap(42, 42, 42)
                        .addComponent(jRadioButton2)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(17, 17, 17))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(99, 99, 99))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(39, 39, 39)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(257, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48)
                .addComponent(sid, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sname, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sclass, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(sdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 1, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton4)))
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(159, 159, 159)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(343, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    String id,name,std,present,attendance;
    id=sid.getText();
    name=sname.getText();
    std=sclass.getText();
      attendance="";
    SimpleDateFormat sf=new SimpleDateFormat("yyyy-MM-dd");
              present=sf.format(sdate.getDate());
              if(jRadioButton1.isSelected())
                  attendance="Present";
                  
              
              if(jRadioButton2.isSelected())
              
                  attendance="Absent";
                
              
            
                  try{
               Class.forName("java.sql.DriverManager");
        Connection con=(Connection) DriverManager.getConnection
            ("jdbc:mysql://localhost:3306/schoolmanagement","root","Mp@0509");
        Statement st=(Statement) con.createStatement();
        int search=0;
         switch(jComboBox1.getSelectedIndex()){
          case 0:
              String query="Select name from satt1 where id='"+id+"' and present='"+present+"';";
              ResultSet rs=st.executeQuery(query);
              search=0;
              while(rs.next()){
                  name=rs.getString("name");
                  search++;
              }
              if(search!=0){
                  JOptionPane.showMessageDialog(this,"Already registered your Attendance");
              }
              else{
                   String que="Insert into Satt1 values('"+id+"','"+name+"','"+std+"','"+present+"','"+attendance+"');";
        st.executeUpdate(que);
        JOptionPane.showMessageDialog(this,name+" Attendance added successfully... ");
              }
        break;
            
          case 1:
              String query1="Select name from satt2 where id='"+id+"' and present='"+present+"';";
              ResultSet rs1=st.executeQuery(query1);
              search=0;
              while(rs1.next()){
                  name=rs1.getString("name");
                  search++;
              }
              if(search!=0){
                  JOptionPane.showMessageDialog(this,"Already Registered your Attendance");
              }
              else{ 
                  String att1query="Insert into Satt2 values('"+id+"','"+name+"','"+std+"','"+present+"','"+attendance+"');";
                st.executeUpdate(att1query);
                 JOptionPane.showMessageDialog(this,name+"  Attendance added successfully... ");}
              break;
          case 2:
              String query2="Select name from satt3 where id='"+id+"' and present='"+present+"';";
              ResultSet rs3=st.executeQuery(query2);
              search=0;
              while(rs3.next()){
                  name=rs3.getString("name");
         
                  search++;
              }
              if(search!=0){
                  JOptionPane.showMessageDialog(this,"Already Registered Your Attendnace");
              }
              else{
                   String que="Insert into Satt3 values('"+id+"','"+name+"','"+std+"','"+present+"','"+attendance+"');";
        st.executeUpdate(que);
        JOptionPane.showMessageDialog(this,name+" Attendance added successfully... ");
              }
        break;
              
            
          case 3:
              String query3="Select name from satt4 where id='"+id+"' and present='"+present+"';";
              ResultSet rs4=st.executeQuery(query3);
              search=0;
              while(rs4.next()){
                  name=rs4.getString("name");
 
                  search++;
              }
              if(search!=0){
                  JOptionPane.showMessageDialog(this,"Already Registered Your Attendance");
              }
              else{
                   String que="Insert into Satt4 values('"+id+"','"+name+"','"+std+"','"+present+"','"+attendance+"');";
        st.executeUpdate(que);
        JOptionPane.showMessageDialog(this,name+" Attendance added successfully... ");}
        break;
          case 4:
              String query4="Select name from satt5 where id='"+id+"' and present='"+present+"';";
              ResultSet rs5=st.executeQuery(query4);
              search=0;
              while(rs5.next()){
                  name=rs5.getString("name");
                  search++;
              }
              if(search!=0){
                  JOptionPane.showMessageDialog(this,"");
              }
              else{
              String que="Insert into Satt5 values('"+id+"','"+name+"','"+std+"','"+present+"','"+attendance+"');";
        st.executeUpdate(que);
        JOptionPane.showMessageDialog(this,name+" Attendance added successfully... ");}
        break;
                  }}
        
              catch(Exception e){
                  JOptionPane.showMessageDialog(this,e.getMessage());
              }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           String id,name,course,present,attendance;
      id=search.getText();
      sid.setText(id);
      int search;
       try{
        Class.forName("java.sql.DriverManager");
        Connection con=(Connection) DriverManager.getConnection
            ("jdbc:mysql://localhost:3306/schoolmanagement","root","Mp@0509");
        Statement st=(Statement) con.createStatement();
      switch(jComboBox1.getSelectedIndex()){
          
          case 0:
              String query="Select name,course from admission1 where id='"+id+"';";
              ResultSet rs=st.executeQuery(query);
              search=0;
              while(rs.next()){
                  name=rs.getString("name");
                  course=rs.getString("course");
                  sname.setText(name);
                  sclass.setText(course);
                  search++;
              }
              if(search==0){
                  JOptionPane.showMessageDialog(this,"Please check the Student ID Number....");
              }
              break;
          case 1:
              String query1="Select name,course from admission2 where id='"+id+"';";
              ResultSet rs1=st.executeQuery(query1);
              search=0;
              while(rs1.next()){
                  name=rs1.getString("name");
                  course=rs1.getString("course");
                  sname.setText(name);
                  sclass.setText(course);
                  search++;
              }
              if(search==0){
                  JOptionPane.showMessageDialog(this,"Please check the Student ID Number....");
              }
              break;
          case 2:
              String query2="Select name,course from admission3 where id='"+id+"';";
              ResultSet rs3=st.executeQuery(query2);
              search=0;
              while(rs3.next()){
                  name=rs3.getString("name");
                  course=rs3.getString("course");
                  sname.setText(name);
                  sclass.setText(course);
                  search++;
              }
              if(search==0){
                  JOptionPane.showMessageDialog(this,"Please check the Student ID Number....");
              }
              break;
          case 3:
              String query3="Select name,course from admission4 where id='"+id+"';";
              ResultSet rs4=st.executeQuery(query3);
              search=0;
              while(rs4.next()){
                  name=rs4.getString("name");
                  course=rs4.getString("course");
                  sname.setText(name);
                  sclass.setText(course);
                  search++;
              }
              if(search==0){
                  JOptionPane.showMessageDialog(this,"Please check the Student ID Number....");
              }break;
          case 4:
              String query4="Select name,course from admission5 where id='"+id+"';";
              ResultSet rs5=st.executeQuery(query4);
              search=0;
              while(rs5.next()){
                  name=rs5.getString("name");
                  course=rs5.getString("course");
                  sname.setText(name);
                  sclass.setText(course);
                  search++;
              }
              if(search==0){
                  JOptionPane.showMessageDialog(this,"Please check the Student ID Number....");
              }break;
      }
      }
       catch(Exception e){
           JOptionPane.showMessageDialog(this,e.getMessage());
       }          


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        StuAttendance sa=new StuAttendance();
        sa.show();
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       search.setText("");
       sid.setText("");
       sname.setText("");
       sclass.setText("");
       jRadioButton1.setSelected(false);
       jRadioButton2.setSelected(false);
      
       
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SAttendance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField sclass;
    private com.toedter.calendar.JDateChooser sdate;
    private javax.swing.JTextField search;
    private javax.swing.JTextField sid;
    private javax.swing.JTextField sname;
    // End of variables declaration//GEN-END:variables
}
